[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  let g:lsp_diagnostics_echo_cursor = 1
  let g:lsp_diagnostics_enabled = 1
  let g:lsp_highlight_references_enabled = 1
  let g:lsp_highlights_enabled = 1
  let g:lsp_signs_enabled = 1
  let g:lsp_textprop_enabled = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_fix_on_save = 1
  let g:ale_completion_autoimport = 1
'''

[[plugins]]
repo = 'andreypopp/asyncomplete-ale.vim'
