version: 2
updates:
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: daily
    groups:
      flake-inputs:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(flake)"
