name: push nix cache
runs:
  using: composite
  steps:
    - run: |
        nix shell nixpkgs#awscli2 --command aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE_NAME
        nix shell nixpkgs#awscli2 --command aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE_NAME
    - run: |
        echo $BINARY_CACHE_SECRET_KEY > ./secret.key
        nix store sign --recursive --key-file ./secret.key
      shell: bash
    - run: |
        nix copy --all --to "https://nixcache.pranc1ngpegasus.com?compression=zstd"
      shell: bash
