name: push nix cache
runs:
  using: composite
  steps:
    - run: |
        echo $BINARY_CACHE_SECRET_KEY > ./secret.key
        nix store sign --recursive --key-file ./secret.key
      shell: bash
    - run: |
        nix copy --all --to "https://nixcache.pranc1ngpegasus.com?profile=$AWS_PROFILE_NAME&endpoint=$S3_API_ENDPOINT&compression=zstd"
      shell: bash
