name: setup nix
description: install Determinate Nix and enable FlakeHub Cache
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/determinate-nix-action@4eea0b33e3d1f02ecfe37cf16e7204c424009606 # v3.21.0
    - run: |
        nix shell nixpkgs#awscli2 --command aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE_NAME
        nix shell nixpkgs#awscli2 --command aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE_NAME
