{
  imports = [
    ./nix.nix
    ./determinate.nix
    ./agenix.nix
    ./boot.nix
    ./docker.nix
    ./networking.nix
    ./openssh.nix
    ./tailscale.nix
    ./eternal-terminal.nix
    ./quash.nix
    ./fonts.nix
    ./environment.nix
    ./home-manager.nix
    ./neovim-overlay.nix
    ./llm-agents.nix
  ];
}
