{
  imports = [
    ../common.nix
    ../environment.nix
    ../fonts.nix
    ../home-manager.nix
    ../llm-agents.nix
    ../neovim-overlay.nix
    ../tailscale.nix
    ./agenix.nix
    ./boot.nix
    ./containerd.nix
    ./determinate.nix
    ./environment.nix
    ./networking.nix
    ./nix.nix
    ./openssh.nix
    ./power.nix
    ./tailscale.nix
  ];
}
